### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [NatanSilva31/resort-imobiliaria#1]
Por favor fazer o _rename_ do repositório.

Para o nome de repositório, seguir a convenção onde todas as letras devem ser minúsculas e as palavras separadas com hífen no padrão _kebab-case_ https://coodesh.com/blog/candidates/dicas/convencoes-de-codificacao-do-camelcase-ao-kebab-case/

OBS: O nome do repositório não deve conter a palavra projeto nem o nome da disciplina.

**Comment by NatanSilva31** [comment]
Correção efetuada
